import java.util.StringJoiner;

public class JobData {

  private String employer_name,
      employer_website,
      employer_company_type,
      job_publisher,
      job_employment_type,
      job_title,
      job_apply_link,
      job_apply_is_direct,
      job_description,
      job_is_remote,
      job_posted_at_timestamp,
      job_city,
      job_state,
      job_country,
      job_offer_expiration_timestamp;

  public String getEmployer_name() {
    return employer_name;
  }

  public void setEmployer_name(String employer_name) {
    this.employer_name = employer_name;
  }

  public String getEmployer_website() {
    return employer_website;
  }

  public void setEmployer_website(String employer_website) {
    this.employer_website = employer_website;
  }

  public String getEmployer_company_type() {
    return employer_company_type;
  }

  public void setEmployer_company_type(String employer_company_type) {
    this.employer_company_type = employer_company_type;
  }

  public String getJob_publisher() {
    return job_publisher;
  }

  public void setJob_publisher(String job_publisher) {
    this.job_publisher = job_publisher;
  }

  public String getJob_employment_type() {
    return job_employment_type;
  }

  public void setJob_employment_type(String job_employment_type) {
    this.job_employment_type = job_employment_type;
  }

  public String getJob_title() {
    return job_title;
  }

  public void setJob_title(String job_title) {
    this.job_title = job_title;
  }

  public String getJob_apply_link() {
    return job_apply_link;
  }

  public void setJob_apply_link(String job_apply_link) {
    this.job_apply_link = job_apply_link;
  }

  public String getJob_apply_is_direct() {
    return job_apply_is_direct;
  }

  public void setJob_apply_is_direct(String job_apply_is_direct) {
    this.job_apply_is_direct = job_apply_is_direct;
  }

  public String getJob_description() {
    return job_description;
  }

  public void setJob_description(String job_description) {
    this.job_description = job_description;
  }

  public String getJob_is_remote() {
    return job_is_remote;
  }

  public void setJob_is_remote(String job_is_remote) {
    this.job_is_remote = job_is_remote;
  }

  public String getJob_posted_at_timestamp() {
    return job_posted_at_timestamp;
  }

  public void setJob_posted_at_timestamp(String job_posted_at_timestamp) {
    this.job_posted_at_timestamp = job_posted_at_timestamp;
  }

  public String getJob_city() {
    return job_city;
  }

  public void setJob_city(String job_city) {
    this.job_city = job_city;
  }

  public String getJob_state() {
    return job_state;
  }

  public void setJob_state(String job_state) {
    this.job_state = job_state;
  }

  public String getJob_country() {
    return job_country;
  }

  public void setJob_country(String job_country) {
    this.job_country = job_country;
  }

  public String getJob_offer_expiration_timestamp() {
    return job_offer_expiration_timestamp;
  }

  public void setJob_offer_expiration_timestamp(String job_offer_expiration_timestamp) {
    this.job_offer_expiration_timestamp = job_offer_expiration_timestamp;
  }

  // region toString() -- generated by BoB the Builder of Beans

  @Override
  public String toString() {
    return new StringBuilder()
        .append("     Name of the Employer: " + getEmployer_name() + "\n")
        .append("     Employer Website: " + getEmployer_website() + "\n")
        .append("     Employer Company Type: " + getEmployer_company_type() + "\n")
        .append("     Job Publisher: " + getJob_publisher() + "\n")
        .append("     Employment Type: " + getJob_employment_type() + "\n")
        .append("     Official Title: " + getJob_title() + "\n")
        .append("     Job Application Link: " + getJob_apply_link() + "\n")
        .append("     Is the job application direct?" + getJob_apply_is_direct() + "\n")
        .append("     Description of the Role: " + getJob_description() + "\n")
        .append("     Is the job remote?: " + getJob_is_remote() + "\n")
        .append("     When was the job posted? " + getJob_posted_at_timestamp() + "\n")
        .append("     City: " + getJob_city() + "\n")
        .append("     State: " + getJob_state() + "\n")
        .append("     Country: " + getJob_country() + "\n")
        .append("     When does the job offer expire? " + getJob_offer_expiration_timestamp() + "\n")
        .toString();
  }
}


